apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: blocker-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: bento-receiver
  policyTypes:
  - Ingress
  ingress:
  - from:  
    - podSelector:
        matchLabels:
          app: bento-caller
