apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bento-receiver
  name: bento-receiver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bento-receiver
  template:
    metadata:
      labels:
        app: bento-receiver
    spec:
      containers:
      - image: 558830342743.dkr.ecr.us-east-1.amazonaws.com/bento-test:latest
        name: bento-receiver
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
        env:
          - name: DEST
            value: 'http://localhost:8080/first'

--- 
apiVersion: v1
kind: Service
metadata:
  name: server-entrypoint
spec:
  type: NodePort
  selector:
    app: bento-receiver
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001